import React, { useState } from 'react';
import { 
  Upload, 
  FileText, 
  BrainCircuit, 
  X, 
  Download, 
  MessageSquare 
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

export const MyNotes = ({ notes, onUpload }) => {
  const [selectedNote, setSelectedNote] = useState(null);

  const handleFileUpload = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const newNote = {
      id: Date.now().toString(),
      title: file.name.replace('.pdf', '').replace('.docx', '').replace('.txt', ''),
      subject: 'General',
      content: "AI Analysis in progress...",
      summary: "Analyzing your notes to create a structured summary with diagrams...",
      timestamp: Date.now(),
      status: 'analyzing'
    };
    onUpload(newNote);

    // Mock AI Analysis
    setTimeout(() => {
      const analyzedNote = {
        ...newNote,
        status: 'ready',
        summary: "Based on your notes, here's a structured summary. I've identified 3 key concepts and generated a conceptual diagram for the water cycle process mentioned.",
        content: "Detailed notes with diagrams would appear here..."
      };
      onUpload(analyzedNote);
    }, 3000);
  };

  return (
    <div className="space-y-6 p-8">
      <div className="flex justify-between items-center">
        <h2 className="text-3xl font-bold handwritten">My Notes</h2>
        <label className="cursor-pointer bg-black text-white px-4 py-2 hover:bg-gray-800 transition-all shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] flex items-center gap-2">
          <Upload size={20} />
          <span>Upload New Notes</span>
          <input type="file" className="hidden" onChange={handleFileUpload} accept=".pdf,.docx,.txt" />
        </label>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {notes.map(note => (
          <motion.div 
            key={note.id}
            whileHover={{ scale: 1.02 }}
            onClick={() => setSelectedNote(note)}
            className="p-4 border-2 border-black bg-white shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] cursor-pointer"
          >
            <div className="flex justify-between items-start mb-2">
              <h3 className="font-bold text-lg truncate">{note.title}</h3>
              {note.status === 'analyzing' ? (
                <div className="animate-spin text-blue-600"><BrainCircuit size={20} /></div>
              ) : (
                <FileText className="text-gray-400" />
              )}
            </div>
            <p className="text-sm text-gray-600 line-clamp-2 mb-4">{note.summary}</p>
            <div className="text-xs text-gray-400">{new Date(note.timestamp).toLocaleDateString()}</div>
          </motion.div>
        ))}
      </div>

      <AnimatePresence>
        {selectedNote && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-50"
            onClick={() => setSelectedNote(null)}
          >
            <motion.div 
              initial={{ scale: 0.9, y: 20 }}
              animate={{ scale: 1, y: 0 }}
              className="bg-white border-4 border-black p-8 max-w-2xl w-full max-h-[80vh] overflow-y-auto shadow-[12px_12px_0px_0px_rgba(0,0,0,1)]"
              onClick={e => e.stopPropagation()}
            >
              <div className="flex justify-between items-start mb-6">
                <h2 className="text-3xl font-bold handwritten">{selectedNote.title}</h2>
                <button onClick={() => setSelectedNote(null)} className="p-1 hover:bg-gray-100 rounded-full">
                  <X size={24} />
                </button>
              </div>
              
              <div className="space-y-6">
                <div className="p-4 bg-blue-50 border-2 border-blue-200">
                  <h4 className="font-bold mb-2 flex items-center gap-2">
                    <BrainCircuit size={18} className="text-blue-600" />
                    AI Summary & Analysis
                  </h4>
                  <p className="text-sm text-blue-800">{selectedNote.summary}</p>
                </div>

                <div className="prose max-w-none">
                  <h4 className="font-bold mb-2">Detailed Notes</h4>
                  <p className="text-gray-700">{selectedNote.content}</p>
                  
                  {selectedNote.status === 'ready' && (
                    <div className="mt-8 p-4 border-2 border-dashed border-gray-300 bg-gray-50 flex flex-col items-center justify-center min-h-[200px]">
                      <div className="text-gray-400 mb-2 italic">[Diagram: Conceptual Map of {selectedNote.title}]</div>
                      <p className="text-xs text-gray-400">Diagram generated by AI based on your notes</p>
                    </div>
                  )}
                </div>

                <div className="flex gap-4 pt-4">
                  <button className="flex-1 py-2 bg-black text-white font-bold hover:bg-gray-800 transition-all shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] flex items-center justify-center gap-2">
                    <Download size={18} />
                    Download PDF
                  </button>
                  <button className="flex-1 py-2 border-2 border-black font-bold hover:bg-gray-50 transition-all shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] flex items-center justify-center gap-2">
                    <MessageSquare size={18} />
                    Ask AI about these notes
                  </button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};
